### ISSUE TITLE
Single Cell Movie Interpretation Issues

### ISSUE THREAD

**Issue by roshankern** [WayScience/mitocheck_data#15]
Ultimately, we would like to use representation learning with single-cell movies to see how siRNA's affect whole-video representations (derived with something like [VideoMoCo](https://github.com/tinapan-pt/VideoMoCo) or single-cell image features over time. However we have the following issues to resolve:

- **How to derive single cell movies**
    - Seems like [btrack](https://github.com/quantumjot/BayesianTracker) is best option.
    - Btrack sometimes misses cell divisions and is based on binary segmentation mask so errors occur when nuclei are close or merge.
- **How to synchronize biology with imaging** (ex cells proceed through cell cycle differently, some don't make it through)
- **How to deal with siRNA differences in movies**

**Comment by roshankern** [comment]
**Proposed method 1:**

1. Get single-cell movies for all cells that are tracked for all of movie (or > some percentage of movie). ** This only includes cells that either never divide (and thus don't have tracked children) or divide and aren't tracked as having children.
2. Representation learning of these full length videos.
3. Cluster features.

**Comment by jenna-tomkinson** [comment]
@roshankern 

This issue is a bit outdated. I am assuming this has been resolved, so I will be closing this issue. Feel free to reopen if necessary.
