### ISSUE TITLE
Download Methods Decision Tree

### ISSUE THREAD

**Issue by roshankern** [WayScience/mitocheck_data#3]
### Download Methods:

- ~~Donwload via [idr-py](https://github.com/IDR/idr-py)~~
  - [IDR_downloader.ipynb](../0.download_data/IDR_downloader.ipynb)
  - Files in .webp format, very compressed and easy to work with
  - No high-performance transfer client, ~27 days to download
  - `ResourceError` during download of 7th plate: IDR/idr-py/issues/26
- Donwload via [Aspera](https://idr.openmicroscopy.org/about/download.html)
  - Files in .cd5 ([CellH5](https://github.com/CellH5/cellh5)) format, large and difficult to work with
  - High-performance transfer client, ~6 days to download
  - `OSError` when trying to load with python-bioformats: CellProfiler/python-bioformats/issues/159
  - **This method to download each well with movie as .tiff and annotations as .csv would be optimal**
- Download via [idr bucket](https://www.openmicroscopy.org/2020/11/04/zarr-data.html)
  - Files in [OME-zarr](https://github.com/ome/ome-zarr-py) format, easy to work with
  - Unsure of high-performance transfer client
  - IDR/idr.openmicroscopy.org/issues/160

**Comment by gwaybio** [comment]
To follow up on this thread (@roshankern correct me if i'm getting things mixed up)

We've decided to go with **Route 2** - Download via Aspera. Roshan was able to sidestep the python-bioformats issue in https://github.com/CellProfiler/python-bioformats/issues/159. 

## Reasons to not pursue routes 1 and 3

**Route 1**

- `idr-py` would have been the preferred way, but
    - the package doesn't seem to be actively maintained and
    - the estimated total download time is too long

**Route 3**

- The solution to downloading via the idr bucket required external IDR support in mass-converting the CH5 files to OME-zarr
     - We don't have control over this as a priority and therefore is difficult to estimate time
     - Route 2 has a clear pathway forward

**Comment by roshankern** [comment]
As stated above, we have decided to pursue **Route 2**.
