### ISSUE TITLE
DP Feature Sphering

### ISSUE THREAD

**Issue by roshankern** [WayScience/mitocheck_data#34]
After deriving multiclass models with CP, DP, and CP_and_DP feature combinations in [phenotypic_profiling_model](https://github.com/WayScience/phenotypic_profiling_model), it seems that the CP features tend to outperform DP features, and combining the feature spaces seems to be the best of all:

![image](https://user-images.githubusercontent.com/105665675/230167517-c4d41fed-70cd-4bed-a1c5-7a6a7c389094.png)

![image](https://user-images.githubusercontent.com/105665675/230167546-8f1b9384-48c7-46d6-bdd5-af322268ff63.png)

Given that we expected DP features to outperform CP features, @gwaybio reached out to Dr. Juan Caicedo to see if newer DP models exist that we could use to extract better-performing features. Juan provided direction for using newer DP models but also suggested the following:

> You could try sphering with respect to [the normal class] as well. Even though it is meant to correct for batch effects, it can increase the sensitivity of features to other classes (or treated conditions, in the case of compound screening). You could check that this is the case using UMAP visualizations as well.

Thus, the next step to improve DP feature performance is to sphere the features with respect to the negative control features. Currently, we only perform z-score normalization with respect to these negative control features, as described in [3.normalize_data](https://github.com/WayScience/mitocheck_data/tree/main/3.normalize_data).

**Comment by gwaybio** [comment]
I am attempting to implement this change in `3.normalize_data/normalize_data.py`, but when running:

```python
# get normalization scaler from negative control features (normalization population)
negative_control_data_path = pathlib.Path(
    "../1.idr_streams/extracted_features/negative_control_data/merged_features/"
)
normalization_scaler = get_normalization_scaler(negative_control_data_path)
```

I received the following error:

```python
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[5], line 5
      1 # get normalization scaler from negative control features (normalization population)
      2 negative_control_data_path = pathlib.Path(
      3     "../1.idr_streams/extracted_features/negative_control_data/merged_features/"
      4 )
----> 5 normalization_scaler = get_normalization_scaler(negative_control_data_path)

File ~/repos/mitocheck_data/3.normalize_data/../utils/normalization_utils.py:29, in get_normalization_scaler(norm_pop_path, dataset)
     12 """
     13 get normalization scaler from a normalization population
     14 
   (...)
     26     scaler to be used for data normalization
     27 """
     28 # get normalization population
---> 29 norm_pop_data = compile_mitocheck_batch_data(norm_pop_path, dataset)
     31 # derive normalization scaler
     32 _, norm_pop_feature_data = split_data(norm_pop_data, dataset)

File ~/repos/mitocheck_data/3.normalize_data/../utils/load_utils.py:30, in compile_mitocheck_batch_data(data_path, dataset)
     26 data = pd.DataFrame()
     28 # determine which cols to use for loading (depending on dataset)
     29 # load in first row to get all column names
---> 30 batch_0_row_0 = pd.read_csv(
     31     f"{data_path}/batch_0.csv.gz",
     32     compression="gzip",
     33     index_col=0,
     34     low_memory=False,
     35     nrows=1,
     36 )
     37 cols_to_load = batch_0_row_0.columns.to_list()
     38 # remove unecessary DP column that isnt part of features

File ~/miniconda3/envs/mitocheck_data/lib/python3.8/site-packages/pandas/util/_decorators.py:311, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    305 if len(args) > num_allow_args:
    306     warnings.warn(
    307         msg.format(arguments=arguments),
    308         FutureWarning,
    309         stacklevel=stacklevel,
    310     )
--> 311 return func(*args, **kwargs)

File ~/miniconda3/envs/mitocheck_data/lib/python3.8/site-packages/pandas/io/parsers/readers.py:680, in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)
    665 kwds_defaults = _refine_defaults_read(
    666     dialect,
    667     delimiter,
   (...)
    676     defaults={"delimiter": ","},
    677 )
    678 kwds.update(kwds_defaults)
--> 680 return _read(filepath_or_buffer, kwds)

File ~/miniconda3/envs/mitocheck_data/lib/python3.8/site-packages/pandas/io/parsers/readers.py:575, in _read(filepath_or_buffer, kwds)
    572 _validate_names(kwds.get("names", None))
    574 # Create the parser.
--> 575 parser = TextFileReader(filepath_or_buffer, **kwds)
    577 if chunksize or iterator:
    578     return parser

File ~/miniconda3/envs/mitocheck_data/lib/python3.8/site-packages/pandas/io/parsers/readers.py:933, in TextFileReader.__init__(self, f, engine, **kwds)
    930     self.options["has_index_names"] = kwds["has_index_names"]
    932 self.handles: IOHandles | None = None
--> 933 self._engine = self._make_engine(f, self.engine)

File ~/miniconda3/envs/mitocheck_data/lib/python3.8/site-packages/pandas/io/parsers/readers.py:1217, in TextFileReader._make_engine(self, f, engine)
   1213     mode = "rb"
   1214 # error: No overload variant of "get_handle" matches argument types
   1215 # "Union[str, PathLike[str], ReadCsvBuffer[bytes], ReadCsvBuffer[str]]"
   1216 # , "str", "bool", "Any", "Any", "Any", "Any", "Any"
-> 1217 self.handles = get_handle(  # type: ignore[call-overload]
   1218     f,
   1219     mode,
   1220     encoding=self.options.get("encoding", None),
   1221     compression=self.options.get("compression", None),
   1222     memory_map=self.options.get("memory_map", False),
   1223     is_text=is_text,
   1224     errors=self.options.get("encoding_errors", "strict"),
   1225     storage_options=self.options.get("storage_options", None),
   1226 )
   1227 assert self.handles is not None
   1228 f = self.handles.handle

File ~/miniconda3/envs/mitocheck_data/lib/python3.8/site-packages/pandas/io/common.py:714, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    711     assert isinstance(handle, str)
    712     # error: Incompatible types in assignment (expression has type
    713     # "GzipFile", variable has type "Union[str, BaseBuffer]")
--> 714     handle = gzip.GzipFile(  # type: ignore[assignment]
    715         filename=handle,
    716         mode=ioargs.mode,
    717         **compression_args,
    718     )
    719 else:
    720     handle = gzip.GzipFile(
    721         # No overload variant of "GzipFile" matches argument types
    722         # "Union[str, BaseBuffer]", "str", "Dict[str, Any]"
   (...)
    725         **compression_args,
    726     )

File ~/miniconda3/envs/mitocheck_data/lib/python3.8/gzip.py:173, in GzipFile.__init__(self, filename, mode, compresslevel, fileobj, mtime)
    171     mode += 'b'
    172 if fileobj is None:
--> 173     fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
    174 if filename is None:
    175     filename = getattr(fileobj, 'name', '')

FileNotFoundError: [Errno 2] No such file or directory: '../1.idr_streams/extracted_features/negative_control_data/merged_features/batch_0.csv.gz'
```

**Comment by gwaybio** [comment]
My strategy was to replace the `from sklearn.preprocessing import StandardScaler` with `import pycytominer` and apply `pycytominer.normalize` where `StandardScaler` was previously used.

In addition, I was going to run `pycytominer.normalize(method="spherize", samples="Metadata_treatment == 'negative_control'")` (note this samples argument is hypothetical and will need to be modified).

I would have outputted the DP features and continued passing them through the remaining phenotypic_profiling ML evaluation pipeline

**Comment by roshankern** [comment]
> I am attempting to implement this change in `3.normalize_data/normalize_data.py`, but when running:
> 
> ```python
> # get normalization scaler from negative control features (normalization population)
> negative_control_data_path = pathlib.Path(
>     "../1.idr_streams/extracted_features/negative_control_data/merged_features/"
> )
> normalization_scaler = get_normalization_scaler(negative_control_data_path)
> ```
> 
> I received the following error:

As of now, we do not upload the `idr_stream` outputs as these are too large for Github (~23 GB total). I believe we discussed uploading larger datasets to Figshare in the future but for now I don't think it is viable to fix this reproducibility issue.

**Comment by roshankern** [comment]
> My strategy was to replace the `from sklearn.preprocessing import StandardScaler` with `import pycytominer` and apply `pycytominer.normalize` where `StandardScaler` was previously used.
> 
> In addition, I was going to run `pycytominer.normalize(method="spherize", samples="Metadata_treatment == 'negative_control'")` (note this samples argument is hypothetical and will need to be modified).
> 
> I would have outputted the DP features and continued passing them through the remaining phenotypic_profiling ML evaluation pipeline

Thanks for including this detailed strategy! I will attempt this myself on the machine that has all of the `idr_stream` output data.

**Comment by gwaybio** [comment]
> I believe we discussed uploading larger datasets to Figshare in the future but for now I don't think it is viable to fix this reproducibility issue.

Sounds good. This will be important for the "Data Availability" section of the manuscript. 

It also seems that figshare has a user quota of 20GB. Please use zenodo instead: https://help.zenodo.org/

<img width="550" alt="image" src="https://github.com/WayScience/mitocheck_data/assets/7340421/2d877951-68bd-4b05-859a-66e795b1c6cf">

**Comment by gwaybio** [comment]
(you may need to create a waylab community 😄 )

**Comment by roshankern** [comment]
After testing both only the spherization and the spherization in addition to the standard scaler, it seems that the effect of this spherization is negligible or actually hurts the performance of the model.

There was an increase in "best estimator score" (f1 score after cross validation) of ~0.01. The effects of feature sphering on this repo and `mitocheck_data` can be found at https://github.com/roshankern/mitocheck_data/blob/DP-feature-sphering/4.analyze_data/analyze_data.ipynb and https://github.com/roshankern/phenotypic_profiling_model/blob/use-spherized-features/2.train_model/train_multi_class_models.ipynb respectively.

**Comment by roshankern** [comment]
> (you may need to create a waylab community smile )

Done! Here is the link info:

Collection URL:https://zenodo.org/communities/wayscience/
Above address links directly to your community collection.

Upload URL:https://zenodo.org/deposit/new?c=wayscience
Above address will automatically ensure people who use it will have their record added to your community collection.

Curation URL:https://zenodo.org/communities/wayscience/curate/
Above address links to your private curation URL. You will find all uploads pending your curation.

Harvesting URL:https://zenodo.org/oai2d?verb=ListRecords&set=user-wayscience&metadataPrefix=oai_dc
Above address links to a OAI-PMH feed, which can be used by other digital repositories to harvest this community.

**Comment by jenna-tomkinson** [comment]
@roshankern @gwaybio 

Can this issue be closed, or is this something we need to come back to?

**Comment by gwaybio** [comment]
I'll close it!

Roshan's reply "After testing both only the spherization and the spherization in addition to the standard scaler, it seems that the effect of this spherization is negligible or actually hurts the performance of the model." is the conclusion. I'll also add this discovery to the methods section.
